import type { Task, ClientEntry } from './types'
import type { PlannerState } from './types'

export const SEED_TASKS: Task[] = [
  { id: 1, title: 'İAÜ Dersler Başladı', date: '2026-02-02', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 2, title: '📗 BAU Güz Bütünleme', date: '2026-02-09', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 3, title: 'Melis kuaför', date: '2026-02-11', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 4, title: 'Melis valiz', date: '2026-02-11', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 5, title: 'Pazartesi sunumu hazırla', date: '2026-02-15', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 6, title: 'Beliz Elif Dağlı randevu', date: '2026-03-03', cat: 'Beliz Sağlık', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 7, title: 'Babamın aranması', date: '2026-02-11', cat: 'Baba', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 8, title: 'Gürkan Bey email takip', date: '2026-02-11', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 9, title: 'Belizi okuldan al', date: '2026-02-11', cat: 'Beliz Sağlık', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 10, title: '💑 Barış Melis kaçamak', date: '2026-02-12', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 11, title: 'Beliz sevgi günü', date: '2026-02-13', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 12, title: '✈️ Melis Barış dönüş', date: '2026-02-14', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 13, title: 'Hilal teklif için b2b ile toplantı - betül dönüş', date: '2026-02-14', cat: 'Melis İş', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 14, title: '📗 BAU Bütünleme Son', date: '2026-02-15', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 15, title: '🎁 Babama doğumgünü hediyesi', date: '2026-02-15', cat: 'Baba', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 16, title: 'Babam gmail hallet', date: '2026-02-15', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 17, title: '📗 BAU Güz Not İlan', date: '2026-02-16', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 18, title: 'Beliz yüzme dersi planla - Fırat hoca ayrılmış yerine birini bul', date: '2026-03-16', cat: 'Beliz Gelişim', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 19, title: '💰 Okula 600 TL SON GÜN', date: '2026-02-16', cat: 'Finans', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 20, title: 'Annemle vize evrakları', date: '2026-03-30', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 21, title: '14.00-17.00 DERS - Yoklama kağıtlarını gönder', date: '2026-02-16', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 22, title: 'Elif Dağlı randevu', date: '2026-02-16', cat: 'Beliz Sağlık', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 23, title: '☪️ Ramazan Başlangıcı', date: '2026-02-17', cat: 'Dini', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 24, title: '🏫 Uçurtma Müzesi 09:15', date: '2026-02-17', cat: 'Beliz Okul', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 25, title: 'Turkcell kontratlar', date: '2026-03-05', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 26, title: '🎁 Babama doğumgünü hediyesi', date: '2026-02-18', cat: 'Baba', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 27, title: 'Beliz yüzme dersi planla', date: '2026-03-16', cat: 'Beliz Gelişim', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 28, title: '🕊️ Babaanne Anma Günü', date: '2026-02-18', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 29, title: 'Melis göz doktoru kontrol - 14.20', date: '2026-02-18', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 30, title: 'Beliz diş randevusunu planla + kendininkini de planla', date: '2026-03-16', cat: 'Beliz Sağlık', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 31, title: 'Hong Kong - Joyce için sunum toparla', date: '2026-02-18', cat: 'Melis İş', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 32, title: 'Joyce ile YZTD için nisan\'daki event\'i konuş', date: '2026-02-18', cat: 'Melis İş', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 33, title: 'Eczane: nazalnem, dulcolax, benim yüz kremlerim', date: '2026-03-09', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 34, title: 'Beliz oto koltuğu satış', date: '2026-03-16', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 35, title: 'turkcell ödeme', date: '2026-02-18', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 36, title: '24 Şubat haftası sunumunu hazırla', date: '2026-02-18', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 37, title: 'yztd toplantı', date: '2026-02-18', cat: 'Melis İş', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 38, title: 'scrolli zeynep hn için tarih ver', date: '2026-03-20', cat: 'Melis İş', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 39, title: 'selimcanlar için tarih belirle', date: '2026-02-18', cat: 'Melis İş', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 40, title: 'Hilal için teklif hazırla', date: '2026-02-18', cat: 'Melis İş', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 41, title: 'Yeşim hoca ara', date: '2026-02-18', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 43, title: 'Camii için kıyafet ayarla', date: '2026-02-19', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 44, title: '🔴 Yeterlik Evrak Teslim SON', date: '2026-02-20', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 45, title: '☪️ Ramazan İlk Cuma', date: '2026-02-20', cat: 'Dini', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 46, title: '🎂 Baba Doğum Günü', date: '2026-02-22', cat: 'Baba', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 47, title: '📗 BAU Ders Kayıt Başla', date: '2026-02-23', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 48, title: '📘 İAÜ Ekleme/Bırakma Son', date: '2026-02-23', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 49, title: '📗 BAU Ders Kayıt Son', date: '2026-03-01', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 50, title: 'İftar davet (Bilge)', date: '2026-03-01', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 51, title: '📗 BAU Bahar Dersler Başla', date: '2026-03-04', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 52, title: 'Beliz ara tatil başlıyor', date: '2026-03-13', cat: 'Beliz Okul', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 53, title: '🎂 Barış Doğum Günü', date: '2026-03-15', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 54, title: '☪️ Kadir Gecesi', date: '2026-03-16', cat: 'Dini', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 55, title: '🕊️ Babaanne Anma Günü', date: '2026-03-18', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 56, title: '☪️ Ramazan Bayramı Arife', date: '2026-03-19', cat: 'Dini', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 57, title: '🌙 Ramazan Bayramı', date: '2026-03-20', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 58, title: '🌙 Ramazan Bayramı', date: '2026-03-21', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 59, title: '🌙 Ramazan Bayramı', date: '2026-03-22', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 60, title: '📗 BAU Ara Sınav Başla', date: '2026-04-06', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 61, title: '🎂 Doğumgünüm!', date: '2026-04-12', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 62, title: '📘 İAÜ Ara Sınav Başla', date: '2026-03-23', cat: 'Melis İAÜ', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 63, title: '📗 BAU Ara Sınav Son', date: '2026-04-17', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 64, title: '🕊️ Babaanne Anma Günü', date: '2026-04-18', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 65, title: '🇹🇷 23 Nisan', date: '2026-04-23', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 66, title: '📘 İAÜ Ara Sınav Son', date: '2026-04-24', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 67, title: '🛂 Barış Vize Başvuru!', date: '2026-04-30', cat: 'Finans', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 68, title: '🇹🇷 Emek Günü', date: '2026-05-01', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 69, title: '💍 Evlilik Yıldönümü', date: '2026-05-06', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 70, title: '💰 Bocelli Ödeme SON', date: '2026-05-08', cat: 'Finans', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 71, title: '📗 BAU W Son Gün', date: '2026-05-08', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 72, title: '💐 Anneler Günü', date: '2026-05-11', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 73, title: '🔴 Yeterlik Danışman SON', date: '2026-05-15', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 74, title: '🔴 Jüri Formu SON', date: '2026-05-15', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 75, title: '🕊️ Babaanne Anma Günü', date: '2026-05-18', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 76, title: '🇹🇷 19 Mayıs', date: '2026-05-19', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 77, title: '⚠️ İAÜ Son Ders Hazırlık', date: '2026-05-20', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 78, title: '✈️ Avrupa Seyahati Başla', date: '2026-05-21', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 79, title: '🌍 Avrupa Seyahati', date: '2026-05-22', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 80, title: '⚠️ İAÜ Ders Son Gün!', date: '2026-05-22', cat: 'Çakışma!', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 81, title: '🌍 Avrupa Seyahati', date: '2026-05-23', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 82, title: '🌍 Avrupa Seyahati', date: '2026-05-24', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 83, title: '🌍 Avrupa Seyahati', date: '2026-05-25', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 84, title: '✈️ Avrupa Dönüş', date: '2026-05-26', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 85, title: '☪️ Kurban Arifesi', date: '2026-05-26', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 86, title: '🐑 Kurban Bayramı', date: '2026-05-27', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 87, title: '🐑 Kurban Bayramı', date: '2026-05-28', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 88, title: '🐑 Kurban Bayramı', date: '2026-05-29', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 89, title: '🐑 Kurban Bayramı', date: '2026-05-30', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 90, title: '📝 İAÜ Final Başla', date: '2026-06-01', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 91, title: '⭐ BAU Yeterlik Başla', date: '2026-06-08', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 92, title: '📘 İAÜ Final devam', date: '2026-06-08', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 93, title: '⚠️ ÇİFT ŞAPKA', date: '2026-06-09', cat: 'Çakışma!', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 94, title: '⚠️ ÇİFT ŞAPKA', date: '2026-06-10', cat: 'Çakışma!', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 95, title: '⚠️ ÇİFT ŞAPKA', date: '2026-06-11', cat: 'Çakışma!', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 96, title: '⚠️ ÇİFT ŞAPKA', date: '2026-06-12', cat: 'Çakışma!', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 97, title: '📘 İAÜ Final Son Gün', date: '2026-06-14', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 98, title: '🕊️ Babaanne Anma Günü', date: '2026-06-18', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 99, title: '⭐ Yeterlik SON GÜN', date: '2026-06-19', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 100, title: '📗 BAU Ders Son Gün', date: '2026-06-20', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 101, title: '📘 İAÜ Bütünleme Başla', date: '2026-06-22', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 102, title: '✈️ VENEDİK TK1867 06:50→08:20', date: '2026-06-25', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 103, title: '🇮🇹 Verona & Sirmione Turu', date: '2026-06-25', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 104, title: '⚠️ İAÜ Bütünleme devam!', date: '2026-06-25', cat: 'Çakışma!', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 105, title: '🇮🇹 Vicenza → Padova Turu', date: '2026-06-26', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 106, title: '🏫 Beliz Yaz Tatili', date: '2026-06-26', cat: 'Beliz Okul', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 107, title: '🇮🇹 Treviso → Venedik (tekne)', date: '2026-06-27', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 108, title: '🎤 BOCELLİ San Marco 21:00!', date: '2026-06-27', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 109, title: '🇮🇹 Venedik Adası & Doge Sarayı', date: '2026-06-28', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 110, title: '📘 İAÜ Büt. Son Gün', date: '2026-06-28', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 111, title: '🇮🇹 Murano-Burano-Torcello', date: '2026-06-29', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 112, title: '✈️ İST Dönüş TK1870 20:00→23:35', date: '2026-06-29', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 113, title: '📗 BAU Final Başla', date: '2026-06-30', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 114, title: '📗 BAU Final Son Gün', date: '2026-07-05', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 115, title: '🇹🇷 15 Temmuz', date: '2026-07-15', cat: 'Tatil/Bayram', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 116, title: '🔴 Yeterlik Evrak SON', date: '2026-07-17', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 117, title: '🕊️ Babaanne Anma Günü', date: '2026-07-18', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 118, title: '🕊️ Babaanne Anma Günü', date: '2026-08-18', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 119, title: '🕊️ Babaanne Vefat Yıldönümü', date: '2026-09-18', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 120, title: 'Koç spor topluluğu unutma', date: '2026-03-16', cat: 'Melis Kişisel', pool: 'aile', type: 'weekly', priority: 'med', done: true },
  { id: 121, title: '🕊️ Babaanne Anma Günü', date: '2026-11-18', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 122, title: '🕊️ Babaanne Anma Günü', date: '2026-12-18', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 123, title: 'Annemle 15 mart öncesi kaçamak - sonra yapacağız inşallah', date: '2026-02-16', cat: 'Melis Kişisel', pool: 'aile', type: 'weekly', priority: 'med', done: false },
  { id: 124, title: 'barış seyahat', date: '2026-03-02', cat: 'Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 125, title: 'selimcan ile görüş', date: '2026-03-03', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 126, title: 'Sporu dondur - üyeliği aktive et', date: '2026-03-16', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 127, title: 'elif dağlı randevu', date: '2026-03-03', cat: 'Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 128, title: 'emirhan tarih ver', date: '2026-03-16', cat: 'Genel', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 129, title: 'barış seyahat', date: '2026-03-03', cat: 'Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 131, title: 'marteniçka al', date: '2026-03-04', cat: 'Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 132, title: 'Pazara gidilmesi', date: '2026-03-05', cat: 'Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 140, title: 'Babam ara', date: '2026-03-03', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 143, title: 'Ferdalar iftar', date: '2026-03-17', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 144, title: 'Özgür ö. ziyareti', date: '2026-03-14', cat: 'Dini', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 145, title: 'Ezgi doğumgünü', date: '2026-03-12', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 146, title: 'Pil al', date: '2026-03-05', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 147, title: 'Alışverişi yap', date: '2026-03-03', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 148, title: 'Anneme de yap', date: '2026-03-03', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 150, title: 'Uyan - Beliz\'in durumuna göre okul vs + alışveriş + babam ara + titanik sepetler al english home banyoya mum al + babama pcyi al', date: '2026-03-03', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 151, title: 'abime fatura düştü mü sor', date: '2026-03-04', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 152, title: '13.00 Nihat Hoca ile toplantı', date: '2026-03-06', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: '', done: true },
  { id: 154, title: '16.00 Elif Dağlı Randevu', date: '2026-06-02', cat: 'Beliz Sağlık', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 155, title: '11.30 Joyce ile toplantı', date: '2026-03-03', cat: 'Lâl Project', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 156, title: 'Belize deney yap peluşsuz oda için', date: '2026-03-16', cat: 'Beliz Sağlık', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 157, title: 'Öğleden sonra kuaför', date: '2026-03-06', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 158, title: 'Felsefe Okulu', date: '2026-03-07', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 159, title: 'Akşamüstü fatih barında sergi - gidilebilir mi bakılacak', date: '2026-03-07', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 160, title: 'annemlerle akşam üstü ne yapılabilir bakılacak', date: '2026-03-07', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 161, title: 'https://www.instagram.com/p/DU0gP8bDNac/?igsh=c3dqNmJxOWhhdWE5', date: '2026-03-11', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 162, title: 'Belize bactroban al', date: '2026-03-06', cat: 'Beliz Sağlık', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 163, title: 'Barış göz randevusu', date: '2026-03-12', cat: 'Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 164, title: '16.20 - beliz çocuk doktoru', date: '2026-03-09', cat: 'Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 165, title: '17.00 Beliz cildiye randevu', date: '2026-03-09', cat: 'Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 166, title: 'Melis kan tahlili', date: '2026-03-13', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 167, title: 'Melis - Berrin dahiliye - kan tahlil yaptır öncesinde', date: '2026-03-23', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 168, title: '14.00 Tavuk Dünyası', date: '2026-03-13', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 169, title: 'Akşam annem yemek', date: '2026-03-11', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 170, title: 'Melis tavukd ünyası toplantı', date: '2026-03-14', cat: 'Lâl Project', pool: 'aile', type: 'task', priority: 'med', done: true },
  { id: 171, title: 'Annemi havalimanına bırakacağım', date: '2026-03-15', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 172, title: 'Beliz - göbek bağını gömecek yer', date: '2026-04-01', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 173, title: 'Spor salonuna uğra dondur', date: '2026-03-12', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 174, title: 'Kemal hoca takvim bilgisi gelecek', date: '2026-03-16', cat: 'Melis BAU', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 120, title: 'Koç spor topluluğu unutma', date: '2026-02-16', cat: 'Melis Kişisel', pool: 'aile', type: 'weekly', priority: 'med', done: false },
  { id: 123, title: 'Annemle 15 mart öncesi kaçamak', date: '2026-02-16', cat: 'Melis Kişisel', pool: 'aile', type: 'weekly', priority: 'med', done: false },
  { id: 134, title: 'Beliz günlük yaz', date: '2026-03-16', cat: 'Genel', pool: 'aile', type: 'weekly', priority: 'med', done: false },
  { id: 136, title: 'Beliz oto koltuğu al', date: '2026-03-16', cat: 'Genel', pool: 'aile', type: 'weekly', priority: 'med', done: false },
  { id: 138, title: 'Melis işitme cihazcıya uğra', date: '2026-03-02', cat: 'Melis Kişisel', pool: 'aile', type: 'weekly', priority: 'med', done: true },
  { id: 153, title: 'Melis Beliz Barış vize evrakları', date: '2026-03-16', cat: 'Genel', pool: 'aile', type: 'weekly', priority: 'med', done: false },
  { id: 1000, title: 'Hilal için teklif hazırla', date: '2026-02-18', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1002, title: 'Selimcanlar için tarih belirle', date: '2026-03-04', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1003, title: 'Hilal toplantısı follow-up', date: '2026-03-04', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1005, title: 'Website yenileme brief hazırla', date: '2026-03-01', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1006, title: 'LinkedIn 8 Mart carousel', date: '2026-03-08', cat: 'İçerik / Yazı', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1007, title: 'Q2 müşteri raporları', date: '2026-04-12', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1010, title: 'Joyce ile toplantı (11.30)', date: '2026-03-04', cat: 'YZTD', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1011, title: 'YZTD Medya Telekomünikasyon Çalışma Grubu ile ilgili işleri hatırlat', date: '2026-03-23', cat: 'YZTD', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1012, title: 'InnoEx HK - nihai karar', date: '2026-04-10', cat: 'YZTD', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 1013, title: 'Yeterlik - Yeşim Hoca 20:00', date: '2026-02-19', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1014, title: '🔴 Yeterlik evrak teslim SON GÜN', date: '2026-02-20', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1015, title: '🔴 Yeterlik danışman formu SON', date: '2026-05-15', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1016, title: '⭐ BAU Yeterlik sınavı', date: '2026-06-08', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 1017, title: '⭐ Yeterlik SON GÜN', date: '2026-06-19', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 1018, title: '🔴 Yeterlik evrak SON', date: '2026-07-17', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 1019, title: 'Ders - Yoklama kağıtlarını gönder', date: '2026-02-16', cat: 'İAÜ Derslik', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1020, title: '24 Şubat haftası sunumunu hazırla', date: '2026-02-18', cat: 'İAÜ Derslik', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1021, title: '📘 İAÜ Ekleme/Bırakma son gün', date: '2026-02-23', cat: 'İAÜ Derslik', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1022, title: '⚠️ İAÜ Ders Son Gün', date: '2026-05-22', cat: 'İAÜ Derslik', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 1023, title: '📘 İAÜ Final Son Gün', date: '2026-06-14', cat: 'İAÜ Derslik', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 1024, title: 'Forbes Türkiye - mart sayısı makale taslağı', date: '2026-02-25', cat: 'İçerik / Yazı', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1025, title: 'Inc. Türkiye podcast görüşmesi', date: '2026-03-23', cat: 'İçerik / Yazı', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1026, title: 'HBR Türkiye köşe yazısı - AI tüketici güveni', date: '2026-03-10', cat: 'İçerik / Yazı', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1028, title: 'Joyce (HKTDC) - HK Turkey güncel brief gönder', date: '2026-02-25', cat: 'Network', pool: 'is', type: 'task', priority: 'high', done: true },
  { id: 1030, title: 'NATO Zirvesi Ankara - sponsorluk köprüsü', date: '2026-06-01', cat: 'Network', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1038, title: 'Kemal Hoca toplantı (14.00) - ertelendi', date: '2026-03-05', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1044, title: 'deneme', date: '2026-03-04', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1048, title: 'ömer yeterlilik unutma', date: '2026-03-03', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1772482919333, title: '13.00 nihat hoca sektör temsilciliği toplantı', date: '2026-03-06', cat: 'İAÜ Derslik', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1772482919337, title: '10.30 Mehmet Çolak toplantı', date: '2026-03-09', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1772482919338, title: '12.00 selimcanlarla görüşme', date: '2026-03-09', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1772482919339, title: '14.00 ders', date: '2026-03-09', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1772482919340, title: 'Ankara / moderasyon', date: '2026-03-10', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1772482919341, title: 'Vize randevusu', date: '2026-04-16', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1772482919342, title: 'Sektör temsilcileri toplantısı yapıldı -', date: '2026-03-06', cat: 'İAÜ Derslik', pool: 'is', type: 'task', priority: 'med', done: true },
  { id: 1772482919346, title: '14.00 Kemal hoca ertelendi - tez konusunu netleştir', date: '2026-03-16', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1772482919347, title: 'tez dosyası ama değişecek: https://drive.google.com/drive/folders/1NE_tMgq8MDlrqrIYsbAODebquVuRN0Ih?usp=sharing - buna devam edilecek tezim', date: '2026-03-16', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 900, title: 'Müşteri pipeline haftalık gözden geçir', date: '2026-02-16', cat: 'Lâl Project', pool: 'is', type: 'weekly', priority: 'med', done: true },
  { id: 901, title: 'Akademik okuma - 1 makale', date: '2026-02-16', cat: 'PhD - BAU', pool: 'is', type: 'weekly', priority: 'med', done: true },
  { id: 902, title: 'Network — 2 yeni bağlantı', date: '2026-02-16', cat: 'Network', pool: 'is', type: 'weekly', priority: 'med', done: true },
  { id: 1034, title: 'Scrolli - Zeynep Hanım için tarih ver', date: '2026-03-23', cat: 'Lâl Project', pool: 'is', type: 'weekly', priority: 'med', done: false },
  { id: 1035, title: 'Hong Kong InnoEx booth başvurusu', date: '2026-03-16', cat: 'YZTD', pool: 'is', type: 'weekly', priority: 'med', done: false },
  { id: 1036, title: 'Scrolli zeynep hanım', date: '2026-03-02', cat: '📋 Network - İş geliştirme', pool: 'is', type: 'weekly', priority: 'med', done: true },
  { id: 1037, title: 'Barış ile görüş', date: '2026-03-02', cat: '📋 Network - İş geliştirme', pool: 'is', type: 'weekly', priority: 'med', done: true },
  { id: 1047, title: 'Ömer yeterlilik notlar unutma', date: '2026-03-23', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1772482919334, title: 'claude meetup serilerini araştır', date: '2026-03-02', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1772482919343, title: 'ara tatil - Beliz foto çıktısı', date: '2026-03-16', cat: 'Genel', pool: 'aile', type: 'weekly', priority: 'med', done: false },
  { id: 1772482919344, title: 'claude meetup serilerini araştır', date: '2026-03-02', cat: 'Network', pool: 'is', type: 'weekly', priority: 'high', done: true },
  { id: 1772482919345, title: 'BAP Başvurusu takip et', date: '2026-03-23', cat: 'PhD - BAU', pool: 'is', type: 'weekly', priority: 'med', done: false },
  { id: 2000, title: 'website yenileme — Lâl Project brief hazırla', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 2001, title: 'Inc. Academy teklif formatı oluştur - etkinlik düşün - technoference etkinliğinde yararlan', date: '2026-03-23', cat: 'İçerik / Yazı', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 2002, title: 'podcast serisi konsepti', date: null, cat: 'İçerik / Yazı', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2003, title: 'Türk Dubai Konseyi üyeliği', date: null, cat: 'Network', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2004, title: 'Bilge Karga — Mustafa ile görüş', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2005, title: 'Türkiye-HK stratejik brief güncelle', date: null, cat: 'Network', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2006, title: 'BAU yeterlik tez taslağı', date: null, cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 2007, title: 'AI tüketici güveni — HBR makale planı', date: null, cat: 'İçerik / Yazı', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2008, title: 'YZTD yıllık rapor koordinasyonu', date: null, cat: 'YZTD', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2009, title: 'etsy / shopier — yan gelir araştır', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: '', done: false },
  { id: 2010, title: 'COP31 Antalya içerik paketi', date: null, cat: 'Network', pool: 'is', type: 'backlog', priority: '', done: true },
  { id: 2011, title: 'PR Atölye — PR Filtresi finalize', date: null, cat: 'İçerik / Yazı', pool: 'is', type: 'backlog', priority: 'med', done: true },
  { id: 2012, title: 'Tomorrow.com.tr köşe yazısı', date: null, cat: 'İçerik / Yazı', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2013, title: 'Lâl web sitesi Framer canlıya al', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2014, title: 'BAP projesi başvurusu', date: null, cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 2015, title: 'Erasmus KA131 hareketliliği değerlendir', date: '2026-03-16', cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2016, title: 'Hakemli dergi seçimi + makale başvurusu', date: null, cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 2017, title: 'GEM 2 AI coaching geliştirme', date: null, cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 2018, title: 'TÜBİTAK 1002-A — yeterlik sonrası', date: null, cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: '', done: false },
  { id: 2019, title: 'İAÜ konuk konuşmacı ayarla', date: null, cat: 'İAÜ Derslik', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2020, title: 'IFIG bildiri — kabul takip', date: null, cat: 'Network', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 2021, title: 'ICDS bildiri — kabul takip', date: null, cat: 'Başvuru / Gönderi', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 2022, title: 'ICORIA — Medicana takip', date: null, cat: 'Başvuru / Gönderi', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 2023, title: 'Onur — kesilecek fatura için bilgi verdim dönüş yapılacak', date: '2026-03-16', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 2024, title: 'Emirhan & Selimcan haberleş', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482369812, title: 'aydın üni sempozyum özeti gönderildi takip', date: null, cat: 'Başvuru / Gönderi', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482392261, title: 'website yenileme (lal)', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482395315, title: 'podcast serisini başlat', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 1772482398296, title: 'türk dubai konseyi - katıl', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482407564, title: 'bilge karga - mustafaya yaz', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482409913, title: 'Inc. Academy teklif formatı hazırla', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482412312, title: 'CRM listeni düzenle', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482414879, title: 'bap projesi başvur', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482417212, title: 'hakemli dergi seçimi: claude.ai/chat/c17e0964-344f-47b7-bff4-fbb05681ab80', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482419345, title: 'IFIG bildiri gönderildi takip', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482426112, title: 'ICDS bildiri gönderildi takip', date: null, cat: 'Başvuru / Gönderi', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482429361, title: 'ICORIA medicanaya iletildi takip', date: null, cat: 'Başvuru / Gönderi', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482433662, title: 'IAU konuk ayarla', date: null, cat: 'İAÜ Derslik', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482442297, title: 'Tez konusu Kemal hoca: docs.google.com/document/d/11BI9HtxbxWq7bRYLvzUlnJy1mipUo51s/edit - teknoloji geliştirme ekle', date: null, cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482447645, title: 'Medicana görüşmesi takip - 9 mart\'ta gül hanım ara', date: null, cat: '📋 Network - İş geliştirme', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482454028, title: 'etsy - shopier yan gelir araştır', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482459778, title: 'GEM 2 geliştirme devam', date: null, cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482464044, title: 'Python öğrenmeye mart başla', date: null, cat: 'Genel', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482467828, title: 'İstanbul Modern başvurusu yapıldı', date: null, cat: '📋 Network - İş geliştirme', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482471877, title: 'YZTD medya telekom plan: docs.google.com/document/d/1qfTnmqgSPQyZgQ4oNR1OoRg-WcI3qiQ6/edit', date: '2026-03-23', cat: 'YZTD', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 1772482475594, title: 'fırsat buldukça: scrolli zeynep, paribu art tanışma, erhan meydan buluşma', date: null, cat: '📋 Network - İş geliştirme', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482479027, title: 'onur mevzusu kesilecek fatura', date: '2026-03-23', cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482481778, title: 'GEM live al: claude.ai/chat/32914ec5-4e4b-49f3-bebe-511638c1eef0', date: null, cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482485577, title: 'yeterlik AI modülü: claude.ai/chat/da9551eb-b04e-4f90-95b9-083e0a692e39', date: null, cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482488628, title: 'erasmus hareketliliği: exchange.bau.edu.tr/news/erasmus-ka131-2026-2027', date: null, cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482491928, title: 'yztd kurumsal iletişim', date: null, cat: 'YZTD', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482497695, title: 'Hilal 24.02 toplantı: teklif pulse+signal revize. Eğitim teklifi de iletilebilir.', date: null, cat: 'Lâl Project', pool: 'is', type: 'weekly', priority: 'med', done: false },
  { id: 1772482513111, title: 'Türkiye-HK iş takip edilecek - kapsam gönderildi - hong kong', date: '2026-03-23', cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482695529, title: 'ALES ve YDS planlama', date: null, cat: 'PhD - BAU', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482699921, title: 'Quiz hazırla', date: null, cat: 'İAÜ Derslik', pool: 'is', type: 'backlog', priority: 'med', done: true },
  { id: 1772482706307, title: 'Ödev instruction yaz', date: null, cat: 'İAÜ Derslik', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 1772482715130, title: 'Innonex duyurusunu yap', date: null, cat: 'YZTD', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 1772482897324, title: 'PRAtölye yazısı takip', date: null, cat: 'İçerik / Yazı', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482906881, title: 'Marka pusulası gonca hoca takip et', date: null, cat: 'İAÜ Derslik', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1772482919332, title: 'PRAtölye için kurumsal bakış planı çıkar - sponsorluk dosyası geldi', date: null, cat: 'İAÜ Derslik', pool: 'is', type: 'backlog', priority: 'high', done: false },
  { id: 1773389003491, title: 'Beliz piyano kursu', date: '2026-03-16', cat: 'Beliz Gelişim', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 1773389206721, title: 'Komünite toplantı 14.00', date: '2026-03-26', cat: 'Genel', pool: 'is', type: 'task', priority: '', done: false },
  { id: 1773389268326, title: 'komünite toplantı', date: '2026-03-13', cat: 'Genel', pool: 'is', type: 'task', priority: '', done: true },
  { id: 1773389277646, title: 'komünite toplantı', date: '2026-03-13', cat: 'Genel', pool: 'is', type: 'task', priority: '', done: true },
  { id: 1773389586275, title: 'Futurebright toplantı - 16.00', date: '2026-03-27', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1773390115439, title: 'tecnoference event planlama', date: '2026-03-18', cat: 'Genel', pool: 'is', type: 'task', priority: '', done: false },
  { id: 1773391710382, title: 'vize haftası istanbul aydın', date: '2026-03-23', cat: 'Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773391741494, title: 'barış mısır', date: '2026-04-13', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773391782371, title: 'son ders haftası', date: '2026-05-18', cat: 'İAÜ Derslik', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1773391794727, title: 'seyahatler', date: '2026-05-21', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773391827656, title: 'TBB Eğitim 1', date: '2026-06-04', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1773391833449, title: 'TBB Eğitim 2', date: '2026-06-05', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1773394677594, title: 'makyaj malzemelerini güncelle', date: '2026-03-16', cat: 'Melis Kişisel', pool: 'aile', type: 'weekly', priority: '', done: false },
  { id: 1773394682585, title: 'kadıköyden sigara al', date: '2026-03-13', cat: 'Genel', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 2100000000000, title: '📘 İAÜ Vize Haftası Başlıyor', date: '2026-03-23', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'high', done: false },
  { id: 2100000000001, title: '✈️ Barış Mısır Seyahati', date: '2026-04-13', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000002, title: '🛂 Vize Görüşmesi', date: '2026-04-16', cat: 'Genel', pool: 'aile', type: 'task', priority: 'high', done: false },
  { id: 2100000000003, title: '📘 İAÜ Dersler Son Gün', date: '2026-05-18', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'high', done: false },
  { id: 2100000000004, title: '✈️ Seyahatimiz Başla', date: '2026-05-21', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000005, title: '🌍 Seyahatimiz', date: '2026-05-22', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000006, title: '🌍 Seyahatimiz', date: '2026-05-23', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000007, title: '🌍 Seyahatimiz', date: '2026-05-24', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000008, title: '🌍 Seyahatimiz Son Gün', date: '2026-05-25', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000010, title: '📚 TBB Eğitim - Gün 1', date: '2026-06-04', cat: 'Genel', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 2100000000011, title: '📚 TBB Eğitim - Gün 2', date: '2026-06-05', cat: 'Genel', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 2100000000012, title: '⭐ BAU Yeterlilik Sınavı', date: '2026-06-08', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 2100000000013, title: '📘 İAÜ Bütünleme', date: '2026-06-22', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'high', done: false },
  { id: 2100000000014, title: '🏫 Beliz Yaz Tatili Giriş', date: '2026-06-26', cat: 'Beliz Okul', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000015, title: '🇮🇹 Annemle Venedik Başla', date: '2026-06-25', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000016, title: '🇮🇹 Annemle Venedik', date: '2026-06-26', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000017, title: '🇮🇹 Annemle Venedik', date: '2026-06-27', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000018, title: '🇮🇹 Annemle Venedik', date: '2026-06-28', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000019, title: '🇮🇹 Annemle Venedik Dönüş', date: '2026-06-29', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000020, title: '⏰ İAÜ Vize Haftası YARIN - hazırlıkları tamamla!', date: '2026-03-22', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'high', done: false },
  { id: 2100000000021, title: '⏰ İAÜ vize çalışması başla (1 hafta kaldı)', date: '2026-03-16', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000022, title: '⏰ Barış Mısır seyahati hazırlık - bavul, evrak', date: '2026-04-11', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000023, title: '⏰ Vize görüşmesi YARIN - evrakları hazırla', date: '2026-04-15', cat: 'Genel', pool: 'aile', type: 'task', priority: 'high', done: false },
  { id: 2100000000024, title: '⏰ İAÜ son ders haftası - notları topla', date: '2026-05-11', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000025, title: '⏰ Seyahat 1 hafta sonra - bavul, bilet, konaklama kontrol', date: '2026-05-14', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000026, title: '⏰ İAÜ Final 2 hafta sonra - çalışma planı yap', date: '2026-05-18', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'high', done: false },
  { id: 2100000000027, title: '⏰ İAÜ Final HAFTAYA - yoğun çalışma başla', date: '2026-05-25', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'high', done: false },
  { id: 2100000000028, title: '⏰ TBB Eğitim 1 hafta sonra - hazırlık yap', date: '2026-05-28', cat: 'Genel', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 2100000000029, title: '⏰ BAU Yeterlilik Sınavı 2 hafta sonra - yoğun çalışma!', date: '2026-05-25', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 2100000000030, title: '⏰ BAU Yeterlilik Sınavı HAFTAYA - son tekrar', date: '2026-06-01', cat: 'PhD - BAU', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 2100000000031, title: '⏰ Venedik seyahati 1 hafta sonra - annemle plan yap', date: '2026-06-18', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 2100000000032, title: '⏰ İAÜ Bütünleme HAFTAYA - son çalışma', date: '2026-06-15', cat: 'Melis İAÜ', pool: 'aile', type: 'task', priority: 'high', done: false },
  { id: 1773572026680, title: 'kitap al: iletişimin abc\'si', date: '2026-03-16', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1029, title: 'COP31 Antalya içerik planı', date: '2026-03-20', cat: 'Network', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1773573838419, title: 'akşamüzeri brafa ile toplantı', date: '2026-03-23', cat: 'Genel', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1773574300651, title: 'Brafa toplantısı - sunumdan fiyatı çıkar', date: '2026-03-23', cat: 'İAÜ Derslik', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1027, title: 'Inc. 5000 Türkiye moderasyon hazırlık', date: '2026-04-01', cat: 'İçerik / Yazı', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 1773574584500, title: 'Sabah spor salona uğra - üyelik dondurması ve üyelik + 10.50 doktor randevusu + iau + akşam kadir gecesi kıyafet vs + ertesi gün planlaması', date: '2026-03-16', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773576007447, title: 'Ev: süpürge, filtre, çamaşır makinesi bakım, süt köpürtücü', date: '2026-03-16', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773576011862, title: 'Belize deney - peluşsuz oda ve burun tıkantısı', date: '2026-03-18', cat: 'Beliz Sağlık', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773576017446, title: 'kendime checkup ve diş', date: '2026-03-16', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773576020961, title: 'Spor salonu üyelik konusu - bitiş mayıs', date: '2026-03-16', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773576026512, title: 'medicana dergi konusu', date: null, cat: 'Melis İş', pool: 'aile', type: 'backlog', priority: 'med', done: false },
  { id: 1773576030344, title: 'medicana üniversite iş bilriği konusu', date: '2026-03-16', cat: 'Melis İş', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773576034029, title: 'brafa 23 martta sunum yapılacak - bütçeyi ordan çıkar', date: '2026-03-23', cat: 'Lâl Project', pool: 'is', type: 'backlog', priority: 'med', done: false },
  { id: 1773576037946, title: 'technoference etkinliğin için claude\'u partner olarak al veya google\'ı - kurumsal iletişime yaz', date: '2026-03-16', cat: 'Melis İş', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773576043095, title: 'medicana interpress döngüsü konusu', date: '2026-03-16', cat: 'Melis İş', pool: 'aile', type: 'task', priority: 'med', done: false },
  { id: 1773576048662, title: 'Yeterlilik ai modüllerini çalış ve hangi yöntem hangi konuda uygulanırı çalış', date: '2026-03-16', cat: 'Lâl Project', pool: 'is', type: 'task', priority: 'med', done: false },
  { id: 1772482919336, title: '54bn454', date: '2026-03-02', cat: 'Network - İş geliştirme', pool: 'is', type: 'weekly', priority: 'med', done: false },
  { id: 50001, title: 'Jour Fixe | HTT (12:00)', date: '2026-03-16', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50002, title: 'Jour Fixe | HTT (12:00)', date: '2026-03-23', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50003, title: 'Jour Fixe | HTT (12:00)', date: '2026-03-30', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50004, title: 'Jour Fixe | HTT (12:00)', date: '2026-04-06', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50005, title: 'Jour Fixe | HTT (12:00)', date: '2026-04-13', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50006, title: 'Jour Fixe | HTT (12:00)', date: '2026-04-20', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50007, title: 'Jour Fixe | HTT (12:00)', date: '2026-04-27', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50008, title: 'Jour Fixe | HTT (12:00)', date: '2026-05-04', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50009, title: 'Jour Fixe | HTT (12:00)', date: '2026-05-11', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50010, title: 'Jour Fixe | HTT (12:00)', date: '2026-05-18', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50011, title: 'Jour Fixe | HTT (12:00)', date: '2026-05-25', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50012, title: 'Jour Fixe | HTT (12:00)', date: '2026-06-01', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50013, title: 'Jour Fixe | HTT (12:00)', date: '2026-06-08', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50014, title: 'Jour Fixe | HTT (12:00)', date: '2026-06-15', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50015, title: 'Jour Fixe | HTT (12:00)', date: '2026-06-22', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50016, title: 'Jour Fixe | HTT (12:00)', date: '2026-06-29', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50017, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-03-20', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50018, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-03-27', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50019, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-04-03', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50020, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-04-10', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50021, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-04-17', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50022, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-04-24', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50023, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-05-01', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50024, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-05-08', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50025, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-05-15', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50026, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-05-22', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50027, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-05-29', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50028, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-06-05', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50029, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-06-12', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50030, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-06-19', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50031, title: 'HT Türkiye Summit 2026 | Planlama (11:30)', date: '2026-06-26', cat: 'Lâl Project', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50032, title: 'Yztd - genel kurul', date: '2026-03-25', cat: 'YZTD', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50033, title: 'Si Her Guide Session', date: '2026-03-26', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50034, title: 'Si Her Guide Session', date: '2026-04-09', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50035, title: 'Si Her Guide Session', date: '2026-04-23', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50036, title: 'Si Her Guide Session', date: '2026-05-07', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50037, title: 'Si Her Guide Session', date: '2026-05-21', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50038, title: 'Si Her Guide Session', date: '2026-06-04', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50039, title: 'Si Her Guide Session', date: '2026-06-18', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50040, title: 'Si Her Trade: Si Her Simulations', date: '2026-04-01', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50041, title: 'Si Her Trade: Si Her Simulations', date: '2026-04-15', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50042, title: 'Si Her Trade: Si Her Simulations', date: '2026-04-29', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50043, title: 'Si Her Trade: Si Her Simulations', date: '2026-05-13', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50044, title: 'Si Her Trade: Si Her Simulations', date: '2026-05-27', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50045, title: 'Si Her Trade: Si Her Simulations', date: '2026-06-10', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50046, title: 'Si Her Trade: Si Her Simulations', date: '2026-06-24', cat: 'Network', pool: 'is', type: 'task', priority: '', done: false },
  { id: 50047, title: 'TBB Eğitim tüm gün', date: '2026-06-04', cat: 'Network', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 50048, title: 'TBB Eğitim tüm gün', date: '2026-06-05', cat: 'Network', pool: 'is', type: 'task', priority: 'high', done: false },
  { id: 50049, title: 'Barış weekly meeting (09:45)', date: '2026-03-17', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50050, title: 'Barış weekly meeting (09:45)', date: '2026-03-24', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50051, title: 'Barış weekly meeting (09:45)', date: '2026-03-31', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50052, title: 'Barış weekly meeting (09:45)', date: '2026-04-07', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50053, title: 'Barış weekly meeting (09:45)', date: '2026-04-14', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50054, title: 'Barış weekly meeting (09:45)', date: '2026-04-21', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50055, title: 'Barış weekly meeting (09:45)', date: '2026-04-28', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50056, title: 'Barış weekly meeting (09:45)', date: '2026-05-05', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50057, title: 'Barış weekly meeting (09:45)', date: '2026-05-12', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50058, title: 'Barış weekly meeting (09:45)', date: '2026-05-19', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50059, title: 'Barış weekly meeting (09:45)', date: '2026-05-26', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50060, title: 'Barış weekly meeting (09:45)', date: '2026-06-02', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50061, title: 'Barış weekly meeting (09:45)', date: '2026-06-09', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50062, title: 'Barış weekly meeting (09:45)', date: '2026-06-16', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50063, title: 'Barış weekly meeting (09:45)', date: '2026-06-23', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50064, title: 'Barış weekly meeting (09:45)', date: '2026-06-30', cat: 'Melis & Barış', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50065, title: 'FERDA İFTAR', date: '2026-03-17', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50066, title: 'Melek Öğretmen Doğumgünü', date: '2026-03-21', cat: 'Beliz Okul', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50067, title: 'RAKUNROLL KAHVALTI', date: '2026-03-22', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50068, title: 'SCHENGEN VİZE TESLİM', date: '2026-04-16', cat: 'Seyahat', pool: 'aile', type: 'task', priority: 'high', done: false },
  { id: 50069, title: 'Yardımcı Maaş', date: '2026-04-01', cat: 'Finans', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50070, title: 'Yardımcı Maaş', date: '2026-05-01', cat: 'Finans', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50071, title: 'Yardımcı Maaş', date: '2026-06-01', cat: 'Finans', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50072, title: 'vacanza kalan işler - w mom', date: '2026-05-04', cat: 'Seyahat', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50073, title: 'Havvakuşum birthday', date: '2026-04-19', cat: 'Aile Genel', pool: 'aile', type: 'task', priority: '', done: false },
  { id: 50074, title: 'Melis - Ada Lina anne doğumgünü', date: '2026-06-20', cat: 'Melis Kişisel', pool: 'aile', type: 'task', priority: '', done: false },
]

export const SEED_COMPLETED: { title: string; doneAt: string }[] = [
  { title: 'bilboyu götür', doneAt: '2026-03-13' },
  { title: 'Ezgi doğumgünü', doneAt: '2026-03-13' },
  { title: '10.30 Mehmet Çolak toplantı', doneAt: '2026-03-13' },
  { title: '12.00 selimcanlarla görüşme', doneAt: '2026-03-13' },
  { title: '14.00 ders', doneAt: '2026-03-13' },
  { title: 'Ankara / moderasyon', doneAt: '2026-03-13' },
  { title: 'Akademik okuma - 1 makale', doneAt: '2026-03-13' },
  { title: 'Network — 2 yeni bağlantı', doneAt: '2026-03-13' },
  { title: 'Scrolli zeynep hanım', doneAt: '2026-03-13' },
  { title: 'Barış ile görüş', doneAt: '2026-03-13' },
  { title: 'claude meetup serilerini araştır', doneAt: '2026-03-13' },
  { title: 'bilboyu götür', doneAt: '2026-03-13' },
  { title: 'Özgür ö. ziyareti', doneAt: '2026-03-13' },
  { title: 'HBR Türkiye köşe yazısı - AI tüketici güveni', doneAt: '2026-03-13' },
  { title: 'komünite toplantı', doneAt: '2026-03-13' },
  { title: 'komünite toplantı', doneAt: '2026-03-13' },
  { title: 'Q2 müşteri raporları', doneAt: '2026-03-13' },
  { title: '🔴 Yeterlik danışman formu SON', doneAt: '2026-03-13' },
  { title: 'Müşteri pipeline haftalık gözden geçir', doneAt: '2026-03-13' },
  { title: 'Koç spor topluluğu unutma', doneAt: '2026-03-15' },
]

export const SEED_CLIENTS: ClientEntry[] = [
  { id: 80001, name: 'Hilal', cat: 'Lâl Project', stage: 'tamamlandi', notes: 'B2B teklif hazırlandı, toplantı yapıldı', pool: 'is', createdAt: '2026-02-14' },
  { id: 80002, name: 'Selimcanlar', cat: 'Lâl Project', stage: 'tamamlandi', notes: 'Tarih belirlendi, görüşme yapıldı', pool: 'is', createdAt: '2026-02-18' },
  { id: 80003, name: 'Scrolli / Zeynep Hn', cat: 'Lâl Project', stage: 'teklif', notes: 'Tarih verilecek', pool: 'is', createdAt: '2026-03-01' },
  { id: 80004, name: 'Joyce / HKTDC', cat: 'YZTD', stage: 'aktif', notes: 'Türkiye-HK stratejik brief, Nisan event', pool: 'is', createdAt: '2026-02-18' },
  { id: 80005, name: 'Onur', cat: 'Lâl Project', stage: 'aktif', notes: 'Fatura kesilecek, bilgi verildi', pool: 'is', createdAt: '2026-03-10' },
  { id: 80006, name: 'Bilge Karga / Mustafa', cat: 'Lâl Project', stage: 'lead', notes: 'Görüşme planlanacak', pool: 'is', createdAt: '2026-03-01' },
  { id: 80007, name: 'Mehmet Çolak', cat: 'Lâl Project', stage: 'tamamlandi', notes: 'Toplantı yapıldı 10 Mart', pool: 'is', createdAt: '2026-03-09' },
  { id: 80008, name: 'Emirhan & Selimcan', cat: 'Lâl Project', stage: 'lead', notes: 'Haberleşilecek', pool: 'is', createdAt: '2026-03-05' },
  { id: 80009, name: 'Inc. Academy', cat: 'Lâl Project', stage: 'teklif', notes: 'Teklif formatı oluşturulacak, technoference', pool: 'is', createdAt: '2026-03-01' },
  { id: 80010, name: 'Opinion AI', cat: 'Lâl Project', stage: 'teklif', notes: 'Teklif verildi, dönüş bekleniyor', pool: 'is', createdAt: '2026-03-15' },
]

export const SEED_DATA: PlannerState = {
  tasks: SEED_TASKS,
  notes: { aile: [], is: [] },
  ideas: [],
  reminders: [],
  completed: SEED_COMPLETED,
  clients: SEED_CLIENTS,
}